Repository luckynode/gift-moment-client, pull requests merged in 2024-12, with the labels that each got.

#10 Feature/2: 내 편지함 페이지
  package-lock.json
  package.json
  src/App.tsx
  src/assets/letters/arrow_left.svg
  src/assets/letters/black_music.svg
  src/assets/letters/blue_envelope.svg
  src/assets/letters/cake.svg
  src/assets/letters/cherry.svg
  src/assets/letters/cloud.svg
  src/assets/letters/heart.svg
  src/assets/letters/mint_envelope.svg
  src/assets/letters/orange_flower.svg
  src/assets/letters/rainbow_star.svg
  src/assets/letters/red_flower.svg
  src/assets/letters/sparkle.svg
  src/assets/letters/strawberry.svg
  src/assets/letters/white_flower.svg
  src/assets/letters/white_star.svg
  src/assets/letters/yellow_music.svg
  src/components/InstructionText.tsx
  src/components/buttons/BackButton.tsx
  src/components/buttons/Button.tsx
  src/components/headers/Header.tsx
  src/components/letters/Cake.tsx
  src/components/letters/CakeItem.tsx
  src/components/letters/LetterDetailModal.tsx
  src/pages/MyLettersPage.tsx
Labels: Feature, 💫경희💫, D-3

#12 Feature/7 : 회원가입 페이지
  index.html
  src/App.tsx
  src/components/SignupComponents.ts
  src/components/buttons/Button.tsx
  src/pages/signup/accountCheck.tsx
  src/pages/signup/accountInput.tsx
  src/pages/signup/getInfo.tsx
  src/routes/login.tsx
  src/routes/mywish.tsx
  src/routes/signup.tsx
  styles.css
Labels: Feature, 🍀선화🍀, D-3

#14 Feature/13: 마이페이지 구성
  src/App.tsx
  src/components/SignupComponents.ts
  src/pages/mypage.tsx
  src/pages/mypageEdit.tsx
  src/routes/mywish.tsx
Labels: Feature, 🍀선화🍀, D-3

#15 Feature/11 : 편지 작성 페이지
  src/App.tsx
  src/assets/home/mascot.svg
  src/components/headers/Header.tsx
  src/components/letters/Cake.tsx
  src/pages/MyLetters.tsx
  src/pages/WriteLetter.tsx
  src/routes/GuestLetters.tsx
  src/routes/LetterSentConfirm.tsx
Labels: Feature, 💫경희💫, D-3

#18 Feature/16:wishlist UI
  src/App.tsx
  src/assets/wishlist/example.jpg
  src/assets/wishlist/plus.svg
  src/assets/wishlist/progress_blue.svg
  src/assets/wishlist/progress_green.svg
  src/assets/wishlist/progress_red.svg
  src/components/UserWishItem.tsx
  src/components/WishItem.tsx
  src/components/buttons/BackButton.tsx
  src/pages/GiftAmount.tsx
  src/pages/InputPrice.tsx
  src/pages/PriceCheck.tsx
  src/pages/SendConfirm.tsx
  src/pages/UserWishCheck.tsx
  src/routes/UserWishList.tsx
  src/routes/WishList.tsx
  src/routes/home.tsx
  src/routes/mywish.tsx
Labels: UI, Feature, 🍀선화🍀, D-3

#20 Feature/17 : 선물 등록 페이지
  src/App.tsx
  src/assets/wishlist/wish_img_input.svg
  src/assets/wishlist/wish_img_modify.svg
  src/routes/AddWish.tsx
  src/routes/AddWishConfirm.tsx
  src/routes/MyLetters.tsx
  src/routes/WishList.tsx
  src/routes/WriteLetter.tsx
Labels: Feature, 💫경희💫, D-3

#24 Feature/23 : 생일자 계좌 송금 신청 페이지
  src/App.tsx
  src/routes/MyLetters.tsx
  src/routes/PaymentRequest.tsx
  src/routes/PaymentRequestComplete.tsx
  src/routes/mywish.tsx
Labels: Feature, 💫경희💫, D-3

#27 Feature/26 : confetti 효과 추가
  package-lock.json
  package.json
  src/assets/home/intro2.svg
  src/components/oauth/Kakao.tsx
  src/routes/home.tsx
  src/routes/login.tsx
Labels: UI, Feature, 🍀선화🍀, D-3

#29 Feautre/28 : 가격 입력 에러 메세지
  src/components/buttons/Button.tsx
  src/pages/price/inputPrice.tsx
  src/pages/userWishDetail.tsx
Labels: UI, 🍀선화🍀, D-3
