Repository luckynode/gift-moment-client, pull requests merged in 2025-01, with the labels that each got.

#34 Feature/30: api 1차 수정
  src/App.tsx
  src/components/BankCompo.tsx
  src/components/oauth/KakaoOauth.tsx
  src/pages/myPage.tsx
  src/pages/myPageEdit.tsx
  src/pages/price/inputPrice.tsx
  src/pages/price/paymentApprove.tsx
  src/pages/price/priceCheck.tsx
  src/pages/price/sendConfirm.tsx
  src/pages/signup/accountCheck.tsx
  src/pages/signup/accountInput.tsx
  src/pages/signup/getInfo.tsx
  src/pages/userWishDetail.tsx
  src/routes/myWish.tsx
  src/routes/userWishList.tsx
  src/routes/wishList.tsx
Labels: Feature, 🍀선화🍀, D-1

#35 Feature/31 : 선물 CRUD 연동
  src/apis/wishItemApi.ts
  src/pages/myWishDetail.tsx
  src/pages/myWishModify.tsx
  src/routes/addWish.tsx
  src/types/api/wishItem.ts
  src/types/common/apiResponse.ts
Labels: Feature, D-1

#37 Feature/30 : api check
  package-lock.json
  package.json
  src/components/loading.tsx
  src/components/oauth/KakaoOauth.tsx
  src/pages/myPage.tsx
  src/pages/myPageEdit.tsx
  src/pages/signup/getInfo.tsx
  src/pages/userWishDetail.tsx
  src/routes/myWish.tsx
  src/routes/userWishList.tsx
  src/routes/wishList.tsx
Labels: Feature, 🍀선화🍀, D-1

#38 Feature/32 : 편지 작성, 조회, 복사 API 연동
  src/App.tsx
  src/apis/guestLetterApi.ts
  src/apis/myLetterApi.ts
  src/components/headers/Header.tsx
  src/routes/guestLetters.tsx
  src/routes/letterSentConfirm.tsx
  src/routes/myLetters.tsx
  src/routes/writeLetter.tsx
  src/types/api/guestLetter.ts
  src/types/api/myLetter.ts
Labels: Feature, 💫경희💫, D-1

#39 Feature/32 :편지 조회(로그인X) api 연동 성공
  src/components/letters/CakeItem.tsx
  src/routes/myLetters.tsx
Labels: Feature, 💫경희💫, D-1

#40 [#30] Fix: uniqueString 적용
  src/App.tsx
  src/components/items/UserWishItem.tsx
  src/routes/userWishList.tsx
Labels: Feature, 🍀선화🍀, D-1

#46 Feature/36: 결제 api 설정
  src/App.tsx
  src/components/items/UserWishItem.tsx
  src/pages/price/inputPrice.tsx
  src/pages/price/paymentApprove.tsx
  src/pages/price/priceCheck.tsx
  src/pages/price/sendConfirm.tsx
  src/routes/userWishList.tsx
Labels: Feature, 🍀선화🍀, D-1

#47 Feature/44 : 선물, 편지 배포환경 테스트
  .github/workflows/deploy.yml
  src/pages/price/sendConfirm.tsx
  src/routes/guestLetters.tsx
  src/routes/letterSentConfirm.tsx
Labels: Deploy, 💫경희💫, D-1

#48 Feature/36: 결제 페이지 api 설정
  src/pages/price/paymentApprove.tsx
  src/pages/price/priceCheck.tsx
  src/pages/price/sendConfirm.tsx
Labels: Feature, 🍀선화🍀, D-1

#53 Feature/41 : 추가 로그인 후 경로이동 값 삭제
  src/pages/price/inputPrice.tsx
Labels: Bugfix, 🍀선화🍀, D-1
